[package]
name = "RootBridge"
type = "contract"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.82.2", directory = "noir-projects/aztec-nr/aztec" }
