[package]
name = "L2AztecBridgeAdapter"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.2", directory="noir-projects/aztec-nr/aztec" }
WarpToadCore = {path = "../WarpToadCore"}